[package]
name = "kujira-fin"
version = "0.8.1"
edition = "2021"
authors = ["Kujira Labs"]
description = "Interfaces for Kujira FIN"
license = "Apache-2.0"
repository = "https://github.com/Team-Kujira/kujira-rs/tree/master/packages/kujira-fin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw20 = { workspace = true }
kujira-std = { path = "../kujira-std", version = "0.8" }