[package]
name = "kujira"
version = "0.8.0"
edition = "2021"
authors = ["Kujira Labs"]
description = "Interfaces and utilities for Kujira cosmwasm contracts"
license = "Apache-2.0"
homepage = "https://kujira.app"
repository = "https://github.com/Team-Kujira/kujira-rs/tree/master/packages/kujira"

[dependencies]
kujira-std = { path = "../kujira-std" }
kujira-ghost = { path = "../kujira-ghost" }
kujira-fin = { path = "../kujira-fin" }
kujira-stable = { path = "../kujira-stable" }
kujira-orca = { path = "../kujira-orca" }
kujira-minke = { path = "../kujira-minke" }
