[package]
name = "kujira-stable"
version = "1.1.0"
edition = "2021"
authors = ["Kujira Labs"]
description = "Interfaces for Kujira's USK stablecoin"
license = "Apache-2.0"
repository = "https://github.com/Team-Kujira/kujira-rs/tree/master/packages/kujira-stable"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
kujira-std = { path = "../kujira-std", version = "1.1.0" }
kujira-fin = { path = "../kujira-fin", version = "1.1.0" }
